Repository openshift-eng/rebasebot, pull requests merged in 2022-11, with the labels that each got.

#18 Do not log commits that were removed from rebase
  rebasebot/bot.py
Labels: approved, lgtm

#17 [OCPCLOUD-1762]: Update rebasebot to create fresh Go mod updates
  rebasebot/bot.py
Labels: approved, lgtm, ok-to-test

#21 OCPCLOUD-1786: Allow to exclude commits from rebase
  README.md
  rebasebot/bot.py
  rebasebot/cli.py
  rebasebot/test.py
Labels: approved

#22 Set empty tuple as a default for emails and commits arg
  rebasebot/cli.py
Labels: approved, lgtm

#19 Add @lobziik and @odvarkadaniel to approvers
  OWNERS
Labels: approved, lgtm, ok-to-test

#23 Remove --allow-bot-squashing flag
  rebasebot/bot.py
  rebasebot/cli.py
Labels: approved, lgtm
